### ISSUE TITLE
DockerHub Version Outdated?

### ISSUE THREAD

**Issue by JackMoseley2001** [SiwatINC/homebridge_gui_unraid#5]
Hello! Thank you for creating this docker image! It's proved incredibly useful for me.

Some of the plugins we use now require NodeJS 16 (e.g. Ring), however it appears the image being pulled from Docker Hub is still using NodeJS 12 - is this something that needs updating manually on Docker Hub?

On setup it seems to run this `/bin/sh -c echo "deb https://deb.nodesource.com/node_12.x focal main" | sudo tee /etc/apt/sources.list.d/nodesource.list` even when using the latest (verified by attempting to install on a fresh new machine as well), although looks like the Dockerfile in this repository should be adding `node_16.x` into the apt source file?

*Edit: This appears to be the Dockerfile that is available on Docker Hub: https://hub.docker.com/r/siwatinc/homebridge_gui_unraid/dockerfile
Which only uses `FROM siwatinc/nodejsubuntu_base_image` not `FROM ghcr.io/siwatinc/node-baseimage:node16`*

Thank you 🙏

**Comment by SiwatS** [comment]
Hi, since DockerHub now charge you monthly for mass repository access, I switched to GitHub's repository, it is here `https://github.com/SiwatINC/homebridge_gui/pkgs/container/homebridge_gui`

**Comment by JackMoseley2001** [comment]
Thank you - how annoying! 

No worries, will attempt to point my UnRaid at that image instead.
